### ISSUE TITLE
Error 8800 Rendering King of the Pride (CS6)

### ISSUE THREAD

**Issue by duxprime** [ndepaola/mtg-autoproxy#19]
I'm trying to make a render of the [King of the Pride](https://scryfall.com/card/mh1/16/king-of-the-pride) card using the latest code and Photoshop CS6. Pretty much every other kind of card works without issue (land, legendary, planeswalker, full art land, etc.), but I'm getting an error with this card specifically:
![image](https://user-images.githubusercontent.com/2328035/87101934-622ac900-c21e-11ea-9716-ee7090b1eba0.png)

What is strange is that this card doesn't appear to be any different than other vanilla cards, so I'm not sure why an error would occur only for it.

**Comment by ndepaola** [comment]
I just tried rendering this card and I had no issues with it. Not sure what to tell you sorry! Maybe try a different art image renamed to King of the Pride.png/.jpg, or see what happens when you run `python get_card_info.py "King of the Pride"` from the command prompt in `scripts`
![Uploading King of the Pride.png…]()

**Comment by duxprime** [comment]
I tried this with a different piece of art that is known to work, and every succeeded fine. So it's not the JSON coming back from Scryfall that is giving the script problems. It seems to be the art. Can you try rendering with this image?
![King of the Pride (Jonathan Kuo)](https://user-images.githubusercontent.com/2328035/87669186-88c79300-c73b-11ea-89c8-0eedc76e99f5.jpg)
